# This app is deployed via Cloud Build as directed by cloudbuild.yaml.
# Do not deploy directly.

runtime: go115
service: go-dev
main: ./go.dev/cmd/frontend

handlers:
  - url: /.*
    secure: always
    script: auto
