# This Cloud Build file is run automatically when commits land in the website repo.
# See https://console.cloud.google.com/cloud-build/triggers?project=golang-org.
# Do not run directly.

steps:
  - name: 'golang'
    args: ["go", "test", "./..."]
    dir: go.dev
  - name: 'golang'
    entrypoint: bash
    args: ["-c", "go run ./cmd/events/ > ./_content/events.yaml"]
    dir: go.dev
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args: ["./go-app-deploy.sh", "--project=go-discovery", "go.dev/app.yaml"]
  - name: 'golang'
    args: [
      "go", "run", "./cmd/versionprune", "--dry_run=false",
      "--project=go-discovery", "--service=go-dev",
    ]
    dir: go.dev

options:
  machineType: E2_HIGHCPU_8
