steps:
  - name: 'mirror.gcr.io/library/golang'
    entrypoint: bash
    args:
      - -c
      - go run ./cmd/events/ > ./data/events.yaml
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.hugo', '-t', 'gcr.io/$PROJECT_ID/hugo', '.']
  - name: 'gcr.io/$PROJECT_ID/hugo'
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.learn.yaml"]
  - name: 'mirror.gcr.io/library/golang'
    args: ["run", "./cmd/versionprune", "--project=$PROJECT_ID", "--service=go-dev"]
  - name: 'mirror.gcr.io/library/golang'
    args: ["run", "./cmd/versionprune", "--project=$PROJECT_ID", "--service=learn-go-dev"]
images:
  - 'gcr.io/$PROJECT_ID/hugo'
