steps:
  - name: 'mirror.gcr.io/library/golang'
    entrypoint: bash
    args:
      - -c
      - go test ./...
  - name: 'mirror.gcr.io/library/golang'
    entrypoint: bash
    args:
      - -c
      - go run ./cmd/events/ > ./data/events.yaml
