# This Cloud Build file is run automatically when commits land in the website repo.
# See https://console.cloud.google.com/cloud-build/triggers?project=golang-org.
# Do not run directly.

steps:
  - name: gcr.io/cloud-builders/git
    args: [
      "clone", "--branch=${_GO_REF}", "--depth=1",
      "https://go.googlesource.com/go", "_gotmp",
    ]
  - name: gcr.io/cloud-builders/git
    dir: _gotmp
    args: [
      "archive", "--format=zip", "--output=../_goroot.zip", "HEAD",
    ]
  - name: mirror.gcr.io/library/golang
    args: ["rm", "-rf", "_gotmp"]
  - name: mirror.gcr.io/library/golang
    args: ["go", "test", "./..."]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: ["./go-app-deploy.sh", "cmd/golangorg/app.yaml"]
  - name: mirror.gcr.io/library/golang
    args: [
      "go", "run", "./cmd/versionprune", "--dry_run=false",
      "--project=$PROJECT_ID", "--service=default",
    ]
    dir: go.dev

options:
  machineType: N1_HIGHCPU_8
