# This Cloud Build file is run automatically when commits land in the website repo.
# See https://console.cloud.google.com/cloud-build/triggers?project=golang-org.
# Do not run directly.

steps:
  - name: 'golang'
    args: ["go", "test", "./..."]
    dir: tour
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: ["./go-app-deploy.sh", "tour/app.yaml"]
  - name: 'golang'
    args: [
      "go", "run", "./cmd/versionprune", "--dry_run=false",
      "--project=$PROJECT_ID", "--service=tour",
    ]

options:
  machineType: E2_HIGHCPU_8
