service: blog
runtime: go112

env_variables:
  GOLANGORG_CHECK_COUNTRY: true
  BLOG_ANALYTICS: |
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-11222381-3"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag("js", new Date());
    gtag("config", "UA-11222381-3");
    gtag("config", "UA-49880327-6");
    </script>

default_expiration: "7d"

handlers:

# Keep these static file handlers in sync with blog.go.
# They're here for improved latency across global regions.
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always
- url: /fonts.css
  static_files: static/fonts.css
  upload: static/fonts.css
  secure: always
- url: /fonts
  static_dir: static/fonts
  http_headers:
    Content-Type: application/font-woff
  secure: always

# This is here to redirect all HTTP traffic to an HTTPS URL
# with the same path.
- url: /.*
  script: auto
  secure: always
