application: golang-org
version: blog-test
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /.*
  script: _go_app

nobuild_files: ^(?!(cmd/blog|code.google.com)/)
