# This app is deployed via Cloud Build as directed by cloudbuild.yaml.
# Do not deploy directly.

service: blog
runtime: go115
main: ./blog

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  BLOG_ANALYTICS: |
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-11222381-3"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag("js", new Date());
    gtag("config", "UA-11222381-3");
    gtag("config", "UA-49880327-6");
    </script>
