# This Cloud Build file is run automatically when commits land in the website repo.
# See https://console.cloud.google.com/cloud-build/triggers?project=golang-org.
# Do not run directly.

steps:
  - name: mirror.gcr.io/library/golang
    args: ["go", "test", "./..."]
    dir: blog
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: ["../go-app-deploy.sh", "app.yaml"]
    dir: blog
  - name: mirror.gcr.io/library/golang
    args: [
      "go", "run", "./cmd/versionprune", "--dry_run=false",
      "--project=$PROJECT_ID", "--service=blog",
    ]
    dir: go.dev

options:
  machineType: E2_HIGHCPU_8
