runtime: go111
service: admin

env_variables:
  GOLANGORG_REDIS_ADDR: 10.0.0.4:6379 # instance "gophercache"
  DATASTORE_PROJECT_ID: golang-org

handlers:
  - url: .*
    script: auto
    secure: always
    login: admin # THIS MUST BE SET

vpc_access_connector:
  name: 'projects/golang-org/locations/us-central1/connectors/golang-vpc-connector'
